apiVersion: v1
kind: Service
metadata: 
  name: postgres-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: postgres
  ports:
    - port: 5432 #need to get to port 3000 on the service
      targetPort: 5432 #to get to port 3000 on the container