apiVersion: v1
kind: Service
metadata: 
  name: redis-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: redis
  ports:
    - port: 6379 #need to get to port 3000 on the service
      targetPort: 6379 #to get to port 3000 on the container